image: alpine/edge
packages:
  - git

secrets:
  - 88cce185-d2ec-4573-9546-e33f36f79bbf

environment:
  # repo and user names on both sr.ht and github
  REPO: typst-collection
  USER: swaits

tasks:
  - clone: |
      git clone --origin origin "git+ssh://git@git.sr.ht/~$USER/$REPO"

  - fetch-all-branches: |
      cd "~/$REPO"
      git fetch origin '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*' --prune

  - setup-github-remote: |
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote add github "git@github.com:$USER/$REPO.git"

  - mirror-to-github: |
      cd "~/$REPO"
      git push --mirror github
