image: alpine/edge
secrets:
  - 88cce185-d2ec-4573-9546-e33f36f79bbf
sources:
  - git+ssh://git@git.sr.ht/~swaits/typst-collection
tasks:
  - mirror-to-github: |
      cd ~/typst-collection
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      # Explicitly fetch all branches & tags
      git fetch origin '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*' --prune
      git remote add github git@github.com:swaits/typst-collection.git
      git push --mirror github
